_schema: _schema
source: /src/

paths:
  uploads: public/uploads
  static: public
collections_config:
  posts:
    path: src/content/posts
    name: Posts
    icon: newspaper
    _enabled_editors:
      - content
  pages:
    path: 'src/content/pages'
    name: Pages
    icon: laptop
    _enabled_editors:
      - visual

timezone: Pacific/Auckland
markdown:
  engine: commonmark
  options:
    xhtml: false
    breaks: false
    linkify: false
    typographer: false
    spaced_lists: false
    sentence_per_line: false
    gfm: true
    code_block_fences: '```'
    escape_snippets_in_code_blocks: false
    treat_indentation_as_code: false
    table: false
    strikethrough: false
    subscript: false
    superscript: false
    heading_ids: false
    attributes: false
